name: ğŸš€ Build and Publish a dotnet tool on nuget.org

on:
  push:
    branches: [main]
    paths:
      - "src/dotnet-test-rerun.csproj"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: â¬‡ï¸ Get latest code
        uses: actions/checkout@v2.3.4

      - name: â„¹ï¸ Setup .NET Core
        uses: actions/setup-dotnet@v1

      - name: ğŸ”ƒ Restore
        run: dotnet restore

      - name: ğŸ”§ Build
        run: dotnet build --configuration Release --no-restore

      - name: ğŸ“ Pack
        run: dotnet pack

      - name: ğŸšš publish
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/dotnet-test-rerun.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
