name: Build and Publish

on:
  push:
    branches: [main]
    paths:
      - "src/dotnet-test-rerun.csproj"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: ‚¨áÔ∏è get latest code
        uses: actions/checkout@latest

      - name: ‚ÑπÔ∏è setup .NET Core
        uses: actions/setup-dotnet@latest

      - name: üöö build, pack & publish
        uses: alirezanet/publish-nuget@latest
        with:
          PROJECT_FILE_PATH: src/dotnet-test-rerun.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_COMMIT: false

  tagged-release:
    name: github tagged release
    runs-on: ubuntu-latest
    needs: [build-and-publish]
    steps:
      - name: ‚úÖ github tagged release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: latest
